server:
  port: 8543

spring:
  application:
    name: LIQUIBASE-TEST
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    #    hibernate:
    #      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
  data:
    redis:
      host: "localhost"
      port: 6379

setting:
  otp:
    expiration-in-minute: 1
  default:
    expiration-in-minute: 60
